'use client'

import { useEffect, useRef, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { 
  PlusCircle, 
  Settings2, 
  History, 
  Bot, 
  Cpu, 
  Zap,
  RefreshCw,
  Rocket,
  Search,
  Share2
} from 'lucide-react'
import { useStore, Message, AgentRole } from '@/lib/store'
import { wsClient, WSEvent } from '@/lib/websocket'
import { chatApi, conversationsApi } from '@/lib/api'
import ChatMessage from './ChatMessage'
import ChatInput from './ChatInput'
import ThinkingIndicator from './ThinkingIndicator'
import toast from 'react-hot-toast'

export default function ChatWindow() {
  const { 
    userId, 
    activeConversationId, 
    messages, 
    setMessages, 
    addMessage,
    setActiveConversation,
    streamingContent,
    appendStreamChunk,
    clearStream,
    setAgentStatus,
    agentStatuses,
    addTask,
    updateTask,
    addAgentActivity,
    setWorkflowGraph,
    setAgentsRunning
  } = useStore()

  const [loading, setLoading] = useState(false)
  const [activeAgent, setActiveAgent] = useState<AgentRole | null>(null)
  const scrollRef = useRef<HTMLDivElement>(null)

  // Scroll to bottom on new messages or streaming
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight
    }
  }, [messages, streamingContent, activeAgent])

  // Setup WebSocket connection
  useEffect(() => {
    if (!activeConversationId) return

    wsClient.connect(activeConversationId)

    // Handle agent thinking events
    const offThinking = wsClient.on('agent_thinking', (e: WSEvent) => {
      const data = e.data as { agent_role: AgentRole }
      setActiveAgent(data.agent_role)
      setAgentStatus(data.agent_role, 'thinking')
      setAgentsRunning(true)
    })

    // Handle message streaming chunks
    const offChunk = wsClient.on('stream_chunk', (e: WSEvent) => {
      const data = e.data as { chunk: string }
      appendStreamChunk(data.chunk)
    })

    // Handle stream completion
    const offDone = wsClient.on('stream_done', (e: WSEvent) => {
      clearStream()
      setActiveAgent(null)
      setAgentsRunning(false)
      // Reset all agent statuses back to idle
      const roles: AgentRole[] = ['product_manager', 'developer', 'marketing', 'analyst', 'orchestrator']
      roles.forEach(r => setAgentStatus(r, 'idle'))
    })

    // Handle real-time agent activities — update the global timeline
    const offActivity = wsClient.on('agent_activity', (e: WSEvent) => {
      addAgentActivity(e.data as any)
      const data = e.data as any
      if (data?.agent_role) {
        setAgentStatus(data.agent_role, data.status === 'completed' ? 'active' : 'thinking')
      }
    })

    // Handle workflow graph updates
    const offWorkflow = wsClient.on('workflow_updated', (e: WSEvent) => {
      const data = e.data as { nodes: any[]; edges: any[] }
      if (data?.nodes) {
        setWorkflowGraph(data.nodes, data.edges || [])
      }
    })

    // Handle real-time task creation
    const offTaskCreated = wsClient.on('task_created', (e: WSEvent) => {
      addTask(e.data as any)
      toast.success('New task generated by AI', { icon: '🚀' })
    })

    // Handle task updates
    const offTaskUpdated = wsClient.on('task_updated', (e: WSEvent) => {
      const data = e.data as { id: string; [key: string]: any }
      updateTask(data.id, data)
    })

    return () => {
      offThinking()
      offChunk()
      offDone()
      offActivity()
      offWorkflow()
      offTaskCreated()
      offTaskUpdated()
      wsClient.disconnect()
    }
  }, [activeConversationId, addMessage, appendStreamChunk, clearStream, setAgentStatus, addTask, updateTask, addAgentActivity, setWorkflowGraph, setAgentsRunning])

  const handleSendMessage = async (text: string) => {
    if (!userId || !activeConversationId) {
      toast.error('Session error. Please refresh.')
      return
    }

    // Add user message locally for immediate feedback
    const userMsg: Message = {
      id: crypto.randomUUID(),
      conversation_id: activeConversationId,
      role: 'user',
      content: text,
      created_at: new Date().toISOString()
    }
    addMessage(userMsg)
    setAgentsRunning(true)

    setLoading(true)
    try {
      const result = await chatApi.sendMessage({
        conversation_id: activeConversationId!,
        user_id: userId,
        message: text,
        autonomous_mode: useStore.getState().autonomousMode
      }) as any

      // Add the final assistant message from the REST response
      if (result?.message) {
        addMessage({
          id: result.message.id,
          conversation_id: activeConversationId,
          role: 'agent',
          agent_role: 'orchestrator',
          content: result.message.content,
          created_at: result.message.created_at || new Date().toISOString()
        })
      }
    } catch (error) {
      toast.error('Failed to send message')
      console.error(error)
    } finally {
      setLoading(false)
    }
  }

  const handleNewSession = async () => {
    if (!userId) return
    
    setLoading(true)
    try {
      const newConv = await conversationsApi.create(userId, "New Analysis Session") as any
      setActiveConversation(newConv.id)
      setMessages([])
      toast.success('Started new session')
    } catch (error) {
      toast.error('Failed to create new session')
      console.error(error)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex flex-col h-full bg-transparent overflow-hidden relative">
      {/* Header */}
      <header className="h-14 flex items-center justify-between px-6 border-b border-white/5 bg-white/[0.02] backdrop-blur-md sticky top-0 z-10">
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1.5">
            <span className="flex h-1.5 w-1.5 rounded-full bg-brand-500 shadow-glow-brand animate-pulse" />
            <h2 className="text-xs font-black text-white uppercase tracking-[0.2em] opacity-80">Command Hub</h2>
          </div>
        </div>

        <div className="flex items-center gap-4">
          <div className="flex items-center gap-1">
            <button className="p-2 text-slate-500 hover:text-white transition-colors" title="History"><History className="h-4 w-4" /></button>
            <button className="p-2 text-slate-500 hover:text-white transition-colors" title="Settings"><Settings2 className="h-4 w-4" /></button>
          </div>
          <div className="w-px h-4 bg-white/10" />
          <button 
            onClick={handleNewSession}
            disabled={loading}
            className="flex items-center gap-2 py-1.5 px-3 rounded-lg bg-brand-500/10 text-brand-400 text-[10px] font-black uppercase tracking-widest hover:bg-brand-500 hover:text-white transition-all disabled:opacity-50 active:scale-95"
          >
            <PlusCircle className="h-3.5 w-3.5" />
            New Project
          </button>
        </div>
      </header>

      {/* Messages Area */}
      <div 
        ref={scrollRef}
        className="flex-1 overflow-y-auto scroll-smooth custom-scrollbar pb-40"
      >
        <div className="max-w-3xl mx-auto py-12 px-6">
          {messages.length === 0 && !loading && (
            <div className="flex flex-col items-center justify-center min-h-[60vh] text-center px-4">
              <motion.div 
                initial={{ scale: 0.8, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                className="w-20 h-20 rounded-3xl bg-brand-600/10 flex items-center justify-center mb-8 border border-brand-500/20 shadow-glow-brand/20 relative"
              >
                <div className="absolute inset-0 bg-brand-500/20 blur-2xl rounded-full" />
                <Zap className="h-10 w-10 text-brand-400 fill-brand-400/20 relative z-10" />
              </motion.div>
              
              <h1 className="text-4xl font-black text-white mb-4 tracking-tighter">
                Neural <span className="text-brand-500">AutoPilot</span>
              </h1>
              <p className="text-slate-500 max-w-sm text-base font-medium leading-relaxed mb-12">
                The next generation of autonomous project execution. Describe your goal to begin.
              </p>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 w-full max-w-2xl">
                {[
                  { title: "Product Manager", desc: "Define goals, user stories & roadmaps", icon: Rocket, msg: "Act as the Product Manager and help me define a roadmap for a new app." },
                  { title: "Lead Developer", desc: "Generate architecture and write code", icon: Cpu, msg: "Act as the Lead Developer and help me design the system architecture." },
                  { title: "Marketing Expert", desc: "Draft campaigns and growth strategies", icon: Share2, msg: "Act as the Marketing Expert and create a growth campaign for my product." },
                  { title: "Data Analyst", desc: "Extract insights and define KPIs", icon: Search, msg: "Act as the Data Analyst and define key metrics for my business." }
                ].map((item) => (
                  <button 
                    key={item.title}
                    onClick={() => handleSendMessage(item.msg)}
                    className="flex flex-col items-start p-5 rounded-[20px] bg-white/[0.03] border border-white/5 hover:border-brand-500/30 hover:bg-white/[0.05] transition-all duration-300 group text-left relative overflow-hidden h-28"
                  >
                    <div className="absolute top-0 right-0 p-4 opacity-[0.03] group-hover:opacity-[0.08] transition-opacity duration-300">
                      <item.icon size={48} />
                    </div>
                    <div className="text-[10px] font-black text-brand-500 uppercase tracking-widest mb-1 transition-transform duration-300 group-hover:-translate-y-1">Agent</div>
                    <div className="text-sm font-bold text-white mb-1 transition-transform duration-300 group-hover:-translate-y-1">{item.title}</div>
                    
                    {/* Words displayed in bottom side on mouse over */}
                    <div className="absolute bottom-5 left-5 right-5 text-xs text-slate-500 opacity-0 translate-y-4 group-hover:opacity-100 group-hover:translate-y-0 transition-all duration-300 pointer-events-none">
                      {item.desc}
                    </div>
                  </button>
                ))}
              </div>
            </div>
          )}

          <AnimatePresence initial={false}>
            {messages.map((msg) => (
              <ChatMessage key={msg.id} message={msg} />
            ))}
            
            {streamingContent && (
              <ChatMessage 
                message={{
                  id: 'streaming',
                  conversation_id: activeConversationId!,
                  role: 'agent',
                  agent_role: activeAgent || 'orchestrator',
                  content: streamingContent,
                  created_at: new Date().toISOString()
                }} 
              />
            )}
            
            {activeAgent && !streamingContent && (
              <ThinkingIndicator role={activeAgent} />
            )}
          </AnimatePresence>
        </div>
      </div>

      {/* Input Area */}
      <ChatInput 
        onSend={handleSendMessage} 
        loading={loading} 
        disabled={!activeConversationId}
      />
    </div>
  )
}

function ArrowRight(props: any) {
  return (
    <svg 
      {...props}
      xmlns="http://www.w3.org/2000/svg" 
      width="24" height="24" 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth="2" 
      strokeLinecap="round" 
      strokeLinejoin="round"
    >
      <path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>
    </svg>
  )
}
