'use client'

import { useEffect, useRef, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { 
  PlusCircle, 
  Settings2, 
  History, 
  Bot, 
  Cpu, 
  Sparkles,
  RefreshCw
} from 'lucide-react'
import { useStore, Message, AgentRole } from '@/lib/store'
import { wsClient, WSEvent } from '@/lib/websocket'
import { chatApi, conversationsApi } from '@/lib/api'
import ChatMessage from './ChatMessage'
import ChatInput from './ChatInput'
import ThinkingIndicator from './ThinkingIndicator'
import toast from 'react-hot-toast'

export default function ChatWindow() {
  const { 
    userId, 
    activeConversationId, 
    messages, 
    setMessages, 
    addMessage,
    streamingContent,
    appendStreamChunk,
    clearStream,
    setAgentStatus,
    agentStatuses,
    addTask,
    updateTask
  } = useStore()

  const [loading, setLoading] = useState(false)
  const [activeAgent, setActiveAgent] = useState<AgentRole | null>(null)
  const scrollRef = useRef<HTMLDivElement>(null)

  // Scroll to bottom on new messages or streaming
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight
    }
  }, [messages, streamingContent, activeAgent])

  // Setup WebSocket connection
  useEffect(() => {
    if (!activeConversationId) return

    wsClient.connect(activeConversationId)

    // Handle agent thinking events
    const offThinking = wsClient.on('agent_thinking', (e: WSEvent) => {
      const data = e.data as { agent_role: AgentRole }
      setActiveAgent(data.agent_role)
      setAgentStatus(data.agent_role, 'thinking')
    })

    // Handle message streaming chunks
    const offChunk = wsClient.on('stream_chunk', (e: WSEvent) => {
      const data = e.data as { chunk: string }
      appendStreamChunk(data.chunk)
    })

    // Handle stream completion
    const offDone = wsClient.on('stream_done', (e: WSEvent) => {
      const data = e.data as { full_message: string; agent_role: AgentRole; message_id: string }
      clearStream()
      setActiveAgent(null)
      addMessage({
        id: data.message_id,
        conversation_id: activeConversationId,
        role: 'agent',
        agent_role: data.agent_role,
        content: data.full_message,
        created_at: new Date().toISOString()
      })
      setAgentStatus(data.agent_role, 'active')
    })

    // Handle real-time task creation
    const offTaskCreated = wsClient.on('task_created', (e: WSEvent) => {
      addTask(e.data as any)
      toast.success('New task generated by AI', { icon: '🚀' })
    })

    // Handle task updates
    const offTaskUpdated = wsClient.on('task_updated', (e: WSEvent) => {
      const data = e.data as { id: string; [key: string]: any }
      updateTask(data.id, data)
    })

    return () => {
      offThinking()
      offChunk()
      offDone()
      offTaskCreated()
      offTaskUpdated()
      wsClient.disconnect()
    }
  }, [activeConversationId, addMessage, appendStreamChunk, clearStream, setAgentStatus, addTask, updateTask])

  const handleSendMessage = async (text: string) => {
    if (!userId || !activeConversationId) {
      toast.error('Session error. Please refresh.')
      return
    }

    // Add user message locally for immediate feedback
    const userMsg: Message = {
      id: crypto.randomUUID(),
      conversation_id: activeConversationId,
      role: 'user',
      content: text,
      created_at: new Date().toISOString()
    }
    addMessage(userMsg)

    setLoading(true)
    try {
      await chatApi.sendMessage({
        conversation_id: activeConversationId!,
        user_id: userId,
        message: text,
        autonomous_mode: useStore.getState().autonomousMode
      })
    } catch (error) {
      toast.error('Failed to send message')
      console.error(error)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex flex-col h-full bg-surface-900">
      {/* Header */}
      <header className="h-16 flex items-center justify-between px-6 border-b border-white/5 bg-surface-800/50 backdrop-blur-sm sticky top-0 z-10">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-brand-600/20 flex items-center justify-center">
            <Sparkles className="h-4 w-4 text-brand-400" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-white tracking-tight">AI Command Center</h2>
            <div className="flex items-center gap-1.5">
              <span className="flex h-1.5 w-1.5 rounded-full bg-green-500 animate-pulse" />
              <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">Multi-Agent Engine Active</span>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button className="btn-ghost p-2" title="History"><History className="h-4 w-4" /></button>
          <button className="btn-ghost p-2" title="Settings"><Settings2 className="h-4 w-4" /></button>
          <div className="w-px h-4 bg-white/10 mx-1" />
          <button className="btn-primary flex items-center gap-2 py-1.5 px-3">
            <PlusCircle className="h-4 w-4" />
            <span className="text-xs">New Session</span>
          </button>
        </div>
      </header>

      {/* Messages Area */}
      <div 
        ref={scrollRef}
        className="flex-1 overflow-y-auto scroll-smooth"
      >
        <div className="max-w-4xl mx-auto py-8">
          {messages.length === 0 && !loading && (
            <div className="flex flex-col items-center justify-center min-h-[50vh] text-center px-4">
              <motion.div 
                initial={{ scale: 0.8, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                className="w-20 h-20 rounded-3xl bg-brand-600/10 flex items-center justify-center mb-6 border border-brand-600/20 shadow-glow-brand"
              >
                <Bot className="h-10 w-10 text-brand-400" />
              </motion.div>
              <h1 className="text-2xl font-bold text-white mb-2">How can AutoPilot help you today?</h1>
              <p className="text-slate-400 max-w-sm text-sm">
                Describe a complex goal, and our agents will work together to plan and execute it.
              </p>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-10 w-full max-w-lg">
                {[
                  "Launch a successful SaaS for developers",
                  "Build a multi-agent marketing campaign",
                  "Automate my customer outreach workflow",
                  "Analyze market trends for AI startups"
                ].map((prompt) => (
                  <button 
                    key={prompt}
                    onClick={() => handleSendMessage(prompt)}
                    className="glass p-4 text-left hover:border-brand-500/50 transition-all group"
                  >
                    <div className="text-xs text-slate-500 mb-1 flex items-center justify-between">
                      Suggestion 
                      <ArrowRight className="h-3 w-3 opacity-0 group-hover:opacity-100 transition-opacity" />
                    </div>
                    <div className="text-xs font-semibold text-slate-200">{prompt}</div>
                  </button>
                ))}
              </div>
            </div>
          )}

          <AnimatePresence initial={false}>
            {messages.map((msg) => (
              <ChatMessage key={msg.id} message={msg} />
            ))}
            
            {streamingContent && (
              <ChatMessage 
                message={{
                  id: 'streaming',
                  conversation_id: activeConversationId!,
                  role: 'agent',
                  agent_role: activeAgent || 'orchestrator',
                  content: streamingContent,
                  created_at: new Date().toISOString()
                }} 
              />
            )}
            
            {activeAgent && !streamingContent && (
              <ThinkingIndicator role={activeAgent} />
            )}
          </AnimatePresence>
        </div>
      </div>

      {/* Input Area */}
      <ChatInput 
        onSend={handleSendMessage} 
        loading={loading} 
        disabled={!activeConversationId}
      />
    </div>
  )
}

function ArrowRight(props: any) {
  return (
    <svg 
      {...props}
      xmlns="http://www.w3.org/2000/svg" 
      width="24" height="24" 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth="2" 
      strokeLinecap="round" 
      strokeLinejoin="round"
    >
      <path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>
    </svg>
  )
}
