'use client'

import DashboardHeader from '@/components/dashboard/DashboardHeader'
import InsightChart from '@/components/dashboard/InsightChart'
import { motion } from 'framer-motion'
import { TrendingUp, Users, Target, Zap, Clock, ArrowUpRight } from 'lucide-react'

export default function InsightsPage() {
  const data1 = [20, 35, 45, 30, 55, 70, 65, 80]
  const data2 = [40, 50, 45, 60, 55, 75, 85, 90]
  const data3 = [15, 25, 20, 35, 30, 45, 40, 50]

  return (
    <div className="p-8 max-w-7xl mx-auto flex flex-col gap-8">
      <DashboardHeader 
        title="Business Insights" 
        subtitle="Data-driven intelligence generated by the Analyst Agent." 
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Main Charts */}
        <div className="lg:col-span-2 flex flex-col gap-8">
          <div className="glass p-8 space-y-10">
            <InsightChart label="User Growth & Engagement" data={data2} color="#6366f1" />
            <InsightChart label="Task Completion Velocity" data={data1} color="#10b981" />
            <InsightChart label="Market Trend Relevancy" data={data3} color="#f59e0b" />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="glass p-6">
              <h4 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-4">Top Converting Channels</h4>
              <div className="space-y-4">
                {[
                  { name: 'X (Twitter)', val: 65, color: 'bg-brand-500' },
                  { name: 'LinkedIn', val: 40, color: 'bg-blue-500' },
                  { name: 'Product Hunt', val: 85, color: 'bg-orange-600' },
                ].map(c => (
                  <div key={c.name} className="space-y-1.5">
                    <div className="flex justify-between text-xs">
                      <span className="text-slate-300 font-medium">{c.name}</span>
                      <span className="text-white font-bold">{c.val}%</span>
                    </div>
                    <div className="h-1 w-full bg-surface-800 rounded-full overflow-hidden">
                      <div className={cn("h-full", c.color)} style={{ width: `${c.val}%` }} />
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="glass p-6 flex flex-col justify-between">
              <div>
                <h4 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-4">Analyst Recommendation</h4>
                <p className="text-sm text-white font-medium leading-relaxed">
                  "Based on current velocity, we should double down on Product Hunt content as it shows 2.4x higher engagement than X."
                </p>
              </div>
              <button className="mt-6 flex items-center gap-2 text-xs font-bold text-brand-400 hover:text-brand-300 transition-colors uppercase tracking-widest">
                Deploy Campaign Update <ArrowUpRight className="h-4 w-4" />
              </button>
            </div>
          </div>
        </div>

        {/* Sidebar Metrics */}
        <div className="flex flex-col gap-6">
          <div className="glass p-6 bg-brand-600/5 border-brand-500/20">
            <div className="flex items-center gap-3 mb-6">
              <div className="p-2 rounded-lg bg-brand-600 shadow-glow-brand">
                <Target className="h-5 w-5 text-white" />
              </div>
              <h3 className="text-lg font-bold text-white">North Star Metric</h3>
            </div>
            <div className="text-4xl font-black text-white mb-1">8,402</div>
            <p className="text-xs text-slate-500 font-medium">Daily Active Processes</p>
            
            <div className="mt-6 flex items-center gap-2 text-green-400 text-xs font-bold">
              <TrendingUp className="h-4 w-4" /> +12.4% vs last week
            </div>
          </div>

          {[
            { label: 'Total Workflow ROI', val: '$14.2k', icon: Zap, color: 'text-yellow-400' },
            { label: 'Time Saved (AI)', val: '124 hrs', icon: Clock, color: 'text-blue-400' },
            { label: 'Team Efficiency', val: '92%', icon: Users, color: 'text-purple-400' },
          ].map(m => (
            <div key={m.label} className="glass p-6 flex items-center gap-4">
              <div className={cn("p-2 rounded-lg bg-surface-800", m.color)}>
                <m.icon className="h-5 w-5" />
              </div>
              <div>
                <div className="text-lg font-bold text-white">{m.val}</div>
                <div className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">{m.label}</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

function cn(...inputs: any[]) {
  return inputs.filter(Boolean).join(' ')
}
