from fastapi import APIRouter, HTTPException
from pathlib import Path
import os
from typing import List, Dict

router = APIRouter(tags=["files"])

OUTPUT_DIR = Path("/home/barath/AutoPilot-AI-Workspace/output")

@router.get("/api/v1/files", response_model=List[Dict[str, str]])
async def list_files():
    """Returns a list of all files generated by agents."""
    if not OUTPUT_DIR.exists():
        return []
    
    files = []
    for root, _, filenames in os.walk(OUTPUT_DIR):
        for f in filenames:
            full_path = Path(root) / f
            rel_path = full_path.relative_to(OUTPUT_DIR)
            files.append({
                "name": f,
                "path": str(rel_path),
                "size": f"{full_path.stat().st_size / 1024:.1f} KB",
                "type": f.split('.')[-1] if '.' in f else 'file'
            })
    return files

@router.get("/api/v1/files/{file_path:path}")
async def get_file_content(file_path: str):
    """Returns the content of a specific file."""
    full_path = (OUTPUT_DIR / file_path).resolve()
    
    # Security: ensure path is within OUTPUT_DIR
    if not str(full_path).startswith(str(OUTPUT_DIR.resolve())):
        raise HTTPException(status_code=403, detail="Access denied")
        
    if not full_path.exists():
        raise HTTPException(status_code=404, detail="File not found")
        
    try:
        with open(full_path, "r") as f:
            return {"content": f.read()}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
