"""
Workflows API — manage visual workflow graphs generated by the AI agents.
Each workflow contains nodes (agents/actions) and edges (connections).
"""

from fastapi import APIRouter, HTTPException, Query
from typing import List, Optional
from datetime import datetime
from uuid import uuid4

from app.models.schemas import Workflow, WorkflowCreate, WorkflowStatus
from app.db.supabase_client import supabase_admin

router = APIRouter(tags=["workflows"])


@router.get("/", response_model=List[dict])
async def get_workflows(
    user_id: str = Query(...),
    status: Optional[str] = Query(None),
):
    query = supabase_admin.table("workflows").select("*").eq("user_id", user_id)
    if status:
        query = query.eq("status", status)
    result = query.order("created_at", desc=True).execute()
    return result.data


@router.post("/", response_model=dict, status_code=201)
async def create_workflow(payload: WorkflowCreate):
    now = datetime.utcnow().isoformat()
    nodes = [n.model_dump() for n in payload.nodes]
    edges = [e.model_dump() for e in payload.edges]
    data = {
        "id": str(uuid4()),
        "user_id": payload.user_id,
        "conversation_id": payload.conversation_id,
        "title": payload.title,
        "description": payload.description,
        "status": WorkflowStatus.DRAFT.value,
        "nodes": nodes,
        "edges": edges,
        "created_at": now,
        "updated_at": now,
    }
    result = supabase_admin.table("workflows").insert(data).execute()
    if not result.data:
        raise HTTPException(status_code=500, detail="Failed to create workflow")
    return result.data[0]


@router.get("/{workflow_id}", response_model=dict)
async def get_workflow(workflow_id: str):
    result = (
        supabase_admin.table("workflows")
        .select("*")
        .eq("id", workflow_id)
        .execute()
    )
    if not result.data:
        raise HTTPException(status_code=404, detail="Workflow not found")
    return result.data[0]


@router.patch("/{workflow_id}/status", response_model=dict)
async def update_workflow_status(workflow_id: str, status: WorkflowStatus):
    result = (
        supabase_admin.table("workflows")
        .update({"status": status.value, "updated_at": datetime.utcnow().isoformat()})
        .eq("id", workflow_id)
        .execute()
    )
    if not result.data:
        raise HTTPException(status_code=404, detail="Workflow not found")
    return result.data[0]


@router.put("/{workflow_id}/graph", response_model=dict)
async def update_workflow_graph(workflow_id: str, nodes: list, edges: list):
    """Update the visual node/edge graph for a workflow."""
    result = (
        supabase_admin.table("workflows")
        .update({
            "nodes": nodes,
            "edges": edges,
            "updated_at": datetime.utcnow().isoformat(),
        })
        .eq("id", workflow_id)
        .execute()
    )
    if not result.data:
        raise HTTPException(status_code=404, detail="Workflow not found")
    return result.data[0]


@router.delete("/{workflow_id}", status_code=204)
async def delete_workflow(workflow_id: str):
    supabase_admin.table("workflows").delete().eq("id", workflow_id).execute()
