import { Message, Task } from './store'

export function exportProjectToMarkdown(projectName: string, messages: Message[], tasks: Task[]) {
  let md = `# 🚀 Project Analysis: ${projectName}\n\n`
  md += `Generated by AutoPilot AI Workspace on ${new Date().toLocaleDateString()}\n\n---\n\n`

  md += `## 🧠 Neural Synthesis (Agent Insights)\n\n`
  messages.filter(m => m.role === 'agent').forEach(m => {
    const role = m.agent_role ? m.agent_role.toUpperCase().replace('_', ' ') : 'ORCHESTRATOR'
    md += `### [${role}]\n${m.content}\n\n`
  })

  md += `\n---\n\n## 📋 Actionable Task Pipeline\n\n`
  if (tasks.length === 0) {
    md += `*No tasks generated yet.*\n`
  } else {
    tasks.forEach((t, i) => {
      const status = t.status === 'completed' ? '[x]' : '[ ]'
      md += `${i + 1}. ${status} **${t.title}** (${t.assigned_agent})\n`
      if (t.description) md += `   > ${t.description}\n`
      md += `\n`
    })
  }

  md += `\n---\n\n*This document was autonomously generated by the MeDo Orchestration Engine.*`

  const blob = new Blob([md], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${projectName.toLowerCase().replace(/\s+/g, '-')}-plan.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
